server:
  port: 8761

spring:
  application:
    name: registry

eureka:
  instance:
    hostname: localhost
  client:
    # 注册中心自身不注册、不拉取注册表
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
